/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package prepa3;

import java.awt.Color;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;

import javax.sound.sampled.*;
import java.io.File;
import java.io.IOException;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author Luis
 */
public class Ventana1 extends javax.swing.JFrame {

    private Clip clip;
    public static String name2 = "";

    /**
     * Creates new form Ventana1
     */
    public Ventana1() {

        initComponents();

        ImageIcon salir2 = new ImageIcon(getClass().getResource("/imagenes/ON.png"));
        Icon fondo2 = new ImageIcon(salir2.getImage().getScaledInstance(on.getWidth(), on.getHeight(), 0));
        on.setIcon(fondo2);
        on.setOpaque(false);
        on.setBorder(null);
        on.setBackground(new Color(0,0,0,0));

        ImageIcon salir = new ImageIcon(getClass().getResource("/imagenes/g.png"));
        Icon fondo = new ImageIcon(salir.getImage().getScaledInstance(exit.getWidth(), exit.getHeight(), 0));
        exit.setIcon(fondo);
        exit.setOpaque(false);
        exit.setBorder(null);
        exit.setBackground(new Color(0,0,0,0));
        
        ImageIcon pali = new ImageIcon(getClass().getResource("/imagenes/pal.png"));
        Icon fondo4 = new ImageIcon(pali.getImage().getScaledInstance(pala.getWidth(), pala.getHeight(), 0));
        pala.setIcon(fondo4);
        pala.setOpaque(false);
        pala.setBorder(null);
        pala.setBackground(new Color(0,0,0,0));
        
        ImageIcon fon = new ImageIcon(getClass().getResource("/imagenes/fondo.png"));
        Icon fondo5 = new ImageIcon(fon.getImage().getScaledInstance(pantalla.getWidth(), pantalla.getHeight(), 0));
        pantalla.setIcon(fondo5);
        
        
        
        
        
        

        this.repaint();

        this.setVisible(true);
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        exit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        next = new javax.swing.JButton();
        on = new javax.swing.JToggleButton();
        pala = new javax.swing.JButton();
        pantalla = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel.setBackground(new java.awt.Color(0, 153, 255));
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/g.png"))); // NOI18N
        exit.setText("X");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        panel.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, 100, 50));

        jLabel1.setText("Nombre:");
        panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        panel.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 310, -1));

        next.setText("Siguiente");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        panel.add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 470, -1, -1));

        on.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ON.png"))); // NOI18N
        on.setText("Music ON");
        on.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onActionPerformed(evt);
            }
        });
        panel.add(on, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 40));

        pala.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pal.png"))); // NOI18N
        pala.setText("PALA");
        pala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                palaActionPerformed(evt);
            }
        });
        panel.add(pala, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 110, 60, 50));

        pantalla.setText("FONDO");
        panel.add(pantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 510));

        getContentPane().add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed

        this.dispose();
    }//GEN-LAST:event_exitActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        this.name2 = name.getText();
        Ventana2 v2 = new Ventana2(this);
    }//GEN-LAST:event_nextActionPerformed

    private void onActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onActionPerformed

        if (on.getText() == "Music ON") {

            ImageIcon salir2 = new ImageIcon(getClass().getResource("/imagenes/ON.png"));
            Icon fondo2 = new ImageIcon(salir2.getImage().getScaledInstance(on.getWidth(), on.getHeight(), 0));
            on.setIcon(fondo2);

            on.setText("Music OFF");
            // Play Audio  File        
            try {
                String filepath = "C:\\Users\\Luis\\Desktop\\musica\\wav\\lo.wav";
                AudioInputStream aui = AudioSystem.getAudioInputStream(new File(filepath).getAbsoluteFile());
                try {
                    clip = AudioSystem.getClip();
                    clip.open(aui);
                    clip.loop(Clip.LOOP_CONTINUOUSLY);
                } catch (IOException | LineUnavailableException e) {
                }
            } catch (IOException | UnsupportedAudioFileException e) {
            }

        } else if (on.getText() == "Music OFF") {

            ImageIcon salir3 = new ImageIcon(getClass().getResource("/imagenes/OFF.png"));
            Icon fondo3 = new ImageIcon(salir3.getImage().getScaledInstance(on.getWidth(), on.getHeight(), 0));
            on.setIcon(fondo3);

            on.setText("Music ON");
            if (clip != null && clip.isRunning()) {
                clip.stop();
            }
        }

    }//GEN-LAST:event_onActionPerformed

    private void palaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_palaActionPerformed
        //
    }//GEN-LAST:event_palaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField name;
    private javax.swing.JButton next;
    private javax.swing.JToggleButton on;
    private javax.swing.JButton pala;
    private javax.swing.JPanel panel;
    private javax.swing.JLabel pantalla;
    // End of variables declaration//GEN-END:variables
}
